const CHANGE_TAB_INDEX_SERVER_DETAIL = 'CHANGE_TAB_INDEX_SERVER_DETAIL';

const SERVER_LIST_REQUEST = "SERVER_LIST_REQUEST";
const SERVER_LIST_SUCCEEDED = "SERVER_LIST_SUCCEEDED";
const SERVER_LIST_FAILED = "SERVER_LIST_FAILED";

const SERVER_DETAIL_REQUEST = "SERVER_DETAIL_REQUEST";
const SERVER_DETAIL_SUCCEEDED = "SERVER_DETAIL_SUCCEEDED";
const SERVER_DETAIL_FAILED = "SERVER_DETAIL_FAILED";

const SERVER_COUNTING_REQUEST = "SERVER_COUNTING_REQUEST";
const SERVER_COUNTING_SUCCEEDED = "SERVER_COUNTING_SUCCEEDED";
const SERVER_COUNTING_FAILED = "SERVER_COUNTING_FAILED";

const ALARM_ITEM_LIST_REQUEST = "ALARM_ITEM_LIST_REQUEST";
const ALARM_ITEM_LIST_SUCCEEDED = "ALARM_ITEM_LIST_SUCCEEDED";
const ALARM_ITEM_LIST_FAILED = "ALARM_ITEM_LIST_FAILED";

const FAILURE_ALARM_LOG_REQUEST = "FAILURE_ALARM_LOG_REQUEST";
const FAILURE_ALARM_LOG_SUCCEEDED = "FAILURE_ALARM_LOG_SUCCEEDED";
const FAILURE_ALARM_LOG_FAILED = "FAILURE_ALARM_LOG_FAILED";

const FAILURE_ALARM_LOG_DETAIL_REQUEST = "FAILURE_ALARM_LOG_DETAIL_REQUEST";
const FAILURE_ALARM_LOG_DETAIL_SUCCEEDED = "FAILURE_ALARM_LOG_DETAIL_SUCCEEDED";
const FAILURE_ALARM_LOG_DETAIL_FAILED = "FAILURE_ALARM_LOG_DETAIL_FAILED";

const AS_REQUEST_LIST_REQUEST = "AS_REQUEST_LIST_REQUEST";
const AS_REQUEST_LIST_SUCCEEDED = "AS_REQUEST_LIST_SUCCEEDED";
const AS_REQUEST_LIST_FAILED = "AS_REQUEST_LIST_FAILED";

const AS_REQUEST_DETAIL_REQUEST = "AS_REQUEST_DETAIL_REQUEST";
const AS_REQUEST_DETAIL_SUCCEEDED = "AS_REQUEST_DETAIL_SUCCEEDED";
const AS_REQUEST_DETAIL_FAILED = "AS_REQUEST_DETAIL_FAILED";

const COMMENT_REGISTRATION_REQUEST = "COMMENT_REGISTRATION_REQUEST";
const COMMENT_REGISTRATION_SUCCEEDED = "COMMENT_REGISTRATION_SUCCEEDED";
const COMMENT_REGISTRATION_FAILED = "COMMENT_REGISTRATION_FAILED";

const AS_REQUEST_TYPE_LIST_REQUEST = "AS_REQUEST_TYPE_LIST_REQUEST";
const AS_REQUEST_TYPE_LIST_SUCCEEDED = "AS_REQUEST_TYPE_LIST_SUCCEEDED";
const AS_REQUEST_TYPE_LIST_FAILED = "AS_REQUEST_TYPE_LIST_FAILED";

const GUEST_NO_LIST_REQUEST = "GUEST_NO_LIST_REQUEST";
const GUEST_NO_LIST_SUCCEEDED = "GUEST_NO_LIST_SUCCEEDED";
const GUEST_NO_LIST_FAILED = "GUEST_NO_LIST_FAILED";

export {
    CHANGE_TAB_INDEX_SERVER_DETAIL,

    SERVER_LIST_REQUEST,
    SERVER_LIST_SUCCEEDED,
    SERVER_LIST_FAILED,

    SERVER_DETAIL_REQUEST,
    SERVER_DETAIL_SUCCEEDED,
    SERVER_DETAIL_FAILED,

    SERVER_COUNTING_REQUEST,
    SERVER_COUNTING_SUCCEEDED,
    SERVER_COUNTING_FAILED,

    ALARM_ITEM_LIST_REQUEST,
    ALARM_ITEM_LIST_SUCCEEDED,
    ALARM_ITEM_LIST_FAILED,

    FAILURE_ALARM_LOG_REQUEST,
    FAILURE_ALARM_LOG_SUCCEEDED,
    FAILURE_ALARM_LOG_FAILED,

    FAILURE_ALARM_LOG_DETAIL_REQUEST,
    FAILURE_ALARM_LOG_DETAIL_SUCCEEDED,
    FAILURE_ALARM_LOG_DETAIL_FAILED,

    AS_REQUEST_LIST_REQUEST,
    AS_REQUEST_LIST_SUCCEEDED,
    AS_REQUEST_LIST_FAILED,

    AS_REQUEST_DETAIL_REQUEST,
    AS_REQUEST_DETAIL_SUCCEEDED,
    AS_REQUEST_DETAIL_FAILED,

    COMMENT_REGISTRATION_REQUEST,
    COMMENT_REGISTRATION_SUCCEEDED,
    COMMENT_REGISTRATION_FAILED,

    AS_REQUEST_TYPE_LIST_REQUEST,
    AS_REQUEST_TYPE_LIST_SUCCEEDED,
    AS_REQUEST_TYPE_LIST_FAILED,

    GUEST_NO_LIST_REQUEST,
    GUEST_NO_LIST_SUCCEEDED,
    GUEST_NO_LIST_FAILED,
}