//Navigation
const GO_BACK = 'GO_BACK';
const OPEN_NAVIGATION_DRAWER = 'OPEN_NAVIGATION_DRAWER';
const CLOSE_NAVIGATION_DRAWER = 'CLOSE_NAVIGATION_DRAWER';
const NAVIGATE_TO_LOGIN_SCREEN = 'NAVIGATE_TO_LOGIN_SCREEN';
const NAVIGATE_TO_STATUS_INFO_SCREEN = 'NAVIGATE_TO_STATUS_INFO_SCREEN';
const NAVIGATE_TO_SERVER_DETAIL_SCREEN = 'NAVIGATE_TO_SERVER_DETAIL_SCREEN';
const NAVIGATE_TO_ALARM_LOG_SCREEN = 'NAVIGATE_TO_ALARM_LOG_SCREEN';
const NAVIGATE_TO_ALARM_LOG_DETAIL_SCREEN = 'NAVIGATE_TO_ALARM_LOG_DETAIL_SCREEN';
const NAVIGATE_TO_SUPPORT_CENTER_SCREEN = 'NAVIGATE_TO_SUPPORT_CENTER_SCREEN';
const NAVIGATE_TO_SUPPORT_VIEW_SCREEN = 'NAVIGATE_TO_SUPPORT_VIEW_SCREEN';
const NAVIGATE_TO_SUPPORT_WRITE_SCREEN = 'NAVIGATE_TO_SUPPORT_WRITE_SCREEN';


export {
    GO_BACK,
    OPEN_NAVIGATION_DRAWER,
    CLOSE_NAVIGATION_DRAWER,
    NAVIGATE_TO_LOGIN_SCREEN,
    NAVIGATE_TO_STATUS_INFO_SCREEN,
    NAVIGATE_TO_SERVER_DETAIL_SCREEN,
    NAVIGATE_TO_ALARM_LOG_SCREEN,
    NAVIGATE_TO_ALARM_LOG_DETAIL_SCREEN,
    NAVIGATE_TO_SUPPORT_CENTER_SCREEN,
    NAVIGATE_TO_SUPPORT_VIEW_SCREEN,
    NAVIGATE_TO_SUPPORT_WRITE_SCREEN,
}

