const AUTHORIZE_REQUEST = "AUTHORIZE_REQUEST";
const AUTHORIZE_SUCCEEDED = "AUTHORIZE_SUCCEEDED";
const AUTHORIZE_FAILED = "AUTHORIZE_FAILED";

const SET_AUTO_LOGIN_TRUE = "SET_AUTO_LOGIN_TRUE";
const SET_AUTO_LOGIN_FALSE = "SET_AUTO_LOGIN_FALSE";

const GET_TOKEN_REQUEST = "GET_TOKEN_REQUEST";
const GET_TOKEN_SUCCEEDED = "GET_TOKEN_SUCCEEDED";
const GET_TOKEN_FAILED = "GET_TOKEN_FAILED";

const VERIFY_REQUEST = "VERIFY_REQUEST";
const VERIFY_SUCCEEDED = "VERIFY_SUCCEEDED";
const VERIFY_FAILED = "VERIFY_FAILED";

export {
  AUTHORIZE_REQUEST,
  AUTHORIZE_SUCCEEDED,
  AUTHORIZE_FAILED,

  SET_AUTO_LOGIN_TRUE,
  SET_AUTO_LOGIN_FALSE,
  
  GET_TOKEN_REQUEST,
  GET_TOKEN_SUCCEEDED,
  GET_TOKEN_FAILED,
  
  VERIFY_REQUEST,
  VERIFY_SUCCEEDED,
  VERIFY_FAILED,
};
