const START_LOADING = 'START_LOADING';
const STOP_LOADING = 'STOP_LOADING';

const SHOW_SUCCESS_ALERT = 'SHOW_SUCCESS_ALERT';
const SHOW_ERROR_ALERT = 'SHOW_ERROR_ALERT';

const SHOW_INFO_DIALOG = 'SHOW_INFO_DIALOG';
const HIDE_INFO_DIALOG = 'HIDE_INFO_DIALOG';

export {
    START_LOADING,
    STOP_LOADING,
    SHOW_SUCCESS_ALERT,
    SHOW_ERROR_ALERT,
    SHOW_INFO_DIALOG,
    HIDE_INFO_DIALOG
}